pipeline {
    agent any

    tools {
        jdk 'JAVA'
        maven 'MAVEN'
    }

    stages {
        stage('Checkout') {
            steps {
                echo '----------------------------------------'
                echo '        CHECKING OUT SOURCE CODE'
                echo '----------------------------------------'
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('Hunt_Career_TestNG_Hybrid_Framework') {
                    echo '----------------------------------------'
                    echo '          BUILDING THE PROJECT'
                    echo '----------------------------------------'
                    bat 'mvn -B clean install'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Hunt_Career_TestNG_Hybrid_Framework') {
                    echo '----------------------------------------'
                    echo '           RUNNING TESTNG TESTS'
                    echo '----------------------------------------'
                    script {
                        try {
                            bat 'mvn -B test'
                        } catch (any) {
                            currentBuild.result = 'UNSTABLE'
                            echo "TestNG tests failed."
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            echo '----------------------------------------'
            echo '        ARCHIVING & PUBLISHING REPORTS'
            echo '----------------------------------------'
            junit testResults: 'Hunt_Career_TestNG_Hybrid_Framework/target/surefire-reports/testng-results.xml', allowEmptyResults: true
            publishHTML(target: [
                allowMissing: true,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'Hunt_Career_TestNG_Hybrid_Framework/test-output/ExtentReports',
                reportFiles: 'extentReport.html',
                reportName: 'Extent Test Report'
            ])
        }
    }
}
