name: Cypress CI

on:
  workflow_call:

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: Hunt_Career_Cypress/node_modules
          key: ${{ runner.os }}-node-cypress-${{ hashFiles('Hunt_Career_Cypress/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-cypress-

      - name: Install Dependencies
        run: npm install
        working-directory: Hunt_Career_Cypress

      - name: Run Cypress Tests
        run: npx cypress run
        working-directory: Hunt_Career_Cypress

      - name: Upload Cypress Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            Hunt_Career_Cypress/cypress/videos
            Hunt_Career_Cypress/cypress/screenshots
