name: Playwright CI

on:
  workflow_call:  # Reusable workflow

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: playwright/node_modules
          key: ${{ runner.os }}-node-playwright-${{ hashFiles('playwright/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-playwright-

      - name: Install Dependencies
        run: npm install
        working-directory: playwright

      - name: Run Playwright Tests
        run: npx playwright test --reporter=html
        working-directory: playwright

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright/playwright-report
