name: Selenium CI

on:
  workflow_call:  # Reusable workflow

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Selenium Tests
        run: mvn clean test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: selenium-test-results
          path: target/surefire-reports
